# Generated by Django 3.1.7 on 2021-05-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default="I don't know, but..."),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(default='myQuestion'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='titleForQuestion', max_length=128),
        ),
    ]
