# Generated by Django 3.1.7 on 2021-06-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210618_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='questions', related_query_name='question', to='app.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.author'),
            preserve_default=False,
        ),
    ]
