# Generated by Django 3.1.7 on 2021-06-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210619_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.AddField(
            model_name='question',
            name='dislikers',
            field=models.ManyToManyField(related_name='disliked_questions', to='app.Author'),
        ),
        migrations.AddField(
            model_name='question',
            name='likers',
            field=models.ManyToManyField(related_name='liked_questions', to='app.Author'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
