# Generated by Django 3.1.7 on 2021-06-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210619_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
